### PR TITLE
modify UI of metric page and fix error message on course detail page

### LINKED ISSUE #41: "Uncaught (in promise) TypeError" when navigating to course
**Bug Description**

Browser: Chrome

Server: Dev

**How to reproduce**
Open DevTools.
Visit the Dashboard.
Select a course.

**Expected Result**
No errors are in the console.

**Actual Result**
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')` appears. 

**More details**
Full stack-trace. 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at CourseDetail.vue:167
(anonymous) @ CourseDetail.vue:167
Promise.then (async)
getData @ CourseDetail.vue:151
mounted @ CourseDetail.vue:133
nt @ vue.runtime.esm.js:1854
Rn @ vue.runtime.esm.js:4213
insert @ vue.runtime.esm.js:3139
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2175
O @ vue.runtime.esm.js:6340
(anonymous) @ vue.runtime.esm.js:6559
En.e._update @ vue.runtime.esm.js:3942
i @ vue.runtime.esm.js:4060
ni.get @ vue.runtime.esm.js:4473
ni.run @ vue.runtime.esm.js:4548
Jn @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
ct @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
ei @ vue.runtime.esm.js:4396
ni.update @ vue.runtime.esm.js:4538
En.e.$forceUpdate @ vue.runtime.esm.js:3963
(anonymous) @ vue.runtime.esm.js:8194
l @ vue.runtime.esm.js:2235
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2175
(anonymous) @ vue.runtime.esm.js:7690
(anonymous) @ vue.runtime.esm.js:336
c @ vue.runtime.esm.js:7390
(anonymous) @ vue.runtime.esm.js:7401
setTimeout (async)
Ya @ vue.runtime.esm.js:7399
(anonymous) @ vue.runtime.esm.js:7722
requestAnimationFrame (async)
(anonymous) @ vue.runtime.esm.js:7357
requestAnimationFrame (async)
Ea @ vue.runtime.esm.js:7356
S @ vue.runtime.esm.js:7714
$a @ vue.runtime.esm.js:7698
remove @ vue.runtime.esm.js:7791
C @ vue.runtime.esm.js:6149
M @ vue.runtime.esm.js:6123
(anonymous) @ vue.runtime.esm.js:6552
En.e._update @ vue.runtime.esm.js:3942
i @ vue.runtime.esm.js:4060
ni.get @ vue.runtime.esm.js:4473
ni.run @ vue.runtime.esm.js:4548
Jn @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
ct @ vue.runtime.esm.js:1906
Promise.then (async)
at @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
ei @ vue.runtime.esm.js:4396
ni.update @ vue.runtime.esm.js:4538
me.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2555
(anonymous) @ vue-router.esm.js:2554
He.updateRoute @ vue-router.esm.js:2013
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ vue-router.esm.js:2000
i @ vue-router.esm.js:1730
i @ vue-router.esm.js:1737
Ee @ vue-router.esm.js:1741
(anonymous) @ vue-router.esm.js:1995
i @ vue-router.esm.js:1730
(anonymous) @ vue-router.esm.js:1734
(anonymous) @ vue-router.esm.js:1980
(anonymous) @ vue-router.esm.js:1808
f @ vue-router.esm.js:1959
i @ vue-router.esm.js:1733
i @ vue-router.esm.js:1737
i @ vue-router.esm.js:1737
(anonymous) @ vue-router.esm.js:1734
(anonymous) @ vue-router.esm.js:1980
(anonymous) @ main.js:52
Promise.then (async)
(anonymous) @ main.js:50
f @ vue-router.esm.js:1959
i @ vue-router.esm.js:1733
i @ vue-router.esm.js:1737
Ee @ vue-router.esm.js:1741
He.confirmTransition @ vue-router.esm.js:1988
He.transitionTo @ vue-router.esm.js:1890
t.push @ vue-router.esm.js:2200
ot.push @ vue-router.esm.js:2581
b @ vue-router.esm.js:458
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Zr.a._wrapper @ vue.runtime.esm.js:6911
```

This has been happening since circa September 2021 but I kept forgetting to file the issue. Sorry!

### PR DESCRIPTION
**Pull request by ho-yi-shiuan**
# Error fix and modify metric page UI

move form of sending data request and lab capture into separate blocks to make it more clear for users. Also fix error message on course detail page.
Fixes #41

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing 
- [ ] Change that requires a documentation update

# How Has This Been Tested?

error fix for course detail page: enter course detail page for courses without capture, there should be no error message in console now.
metric page UI: the form for sending request on metric page should be in the same block with their table.

- [x] Manual Test
- [ ] Unit Test
- [ ] Integration / End-to-End Test

**Test Configuration**:

Chrome Version 96.0.4664.45 (Official Build) (32-bit)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas that are not self-documenting
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings 
- [x] My changes have no unnecessary logging
- [ ] I have added tests that prove my fix is effective or that my feature works, for sufficiently complex features
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Sensitive info like tokens, secrets, and passwords have been removed before submitting

Modified from this article:
Phillip Johnston, “A GitHub Pull Request Template for Your Projects - Embedded Artistry,” Embedded Artistry, Aug. 04, 2017. https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/ (accessed Jul. 22, 2021).

### CODE REVIEW

**Comment by parseccentric** [comment]
Todo

- [ ] Update the data request UI with hints
- [ ] (Future) Update the data request dropdowns to be in 3 rows
- [ ] Fix broken Export CSV button

Tests

- [ ] After clearing data request (summary) type, interaction_type and entity_type should also be cleared
- [ ] If data request is not filled out properly, Export CSV should be disabled
- [ ] If data request is filled out properly, Export CSV should be enabled

File: frontend/src/pages/CourseDetail/CourseDetail.vue [hunk 1]
```diff
@@ -164,18 +164,20 @@ export default {
...
-            return {
-              id: capture.sessionId,
-              captureId: capture.captureId,
-              labName: capture.sessionName,
-              date: start.format("L"),
-              time: `${start.format("LT")}`,
-              duration: moment.duration(start.diff(end)).humanize()
-            }
-          });
+          if(typeof values[2] !== "undefined"){
```
[the remark this answers is not in the document]
Comment (parseccentric) [reply frontend/src/pages/CourseDetail/CourseDetail.vue:167]: Instead of

```
if (something) {
   // do something 1
} 
// do something 2 (which might be nothing)
````


```
if (!something) {
   // do something 2 (which might be nothing)
   
   return; // or return a value
} 
// do something 1
````

File: frontend/src/pages/Metric/Metric.vue [hunk 2]
```diff
@@ -23,6 +23,11 @@
       </v-col>
     </v-row> -->
     
+    <v-row>
+      <v-col>
+        <SectionCard title="Capture Data">
+                <v-container fluid>
+          <template>
     <v-row>
```
Comment (parseccentric) [inline frontend/src/pages/Metric/Metric.vue:31]: Make sure indentation is correct

File: frontend/src/pages/Metric/Metric.vue [hunk 3]
```diff
@@ -148,134 +155,134 @@
...
+              >
+              </v-select>
+              <v-select
+              v-else
+              disabled
+              dense class="ml-3">
+              </v-select>
+            </v-col>
+            <v-btn
+            v-if="(csvCaptureSelected && interactionSelected && entitySelected && typeSelected =='user energy') || (typeSelected =='aggregate interaction' && interactionSelected && csvCaptureSelected) || (typeSelected =='aggregate user' && csvCaptureSelected)"
```
Comment (parseccentric) [inline frontend/src/pages/Metric/Metric.vue:273]: (Future) Refactor this into a function in the JS part of the code

**Review by parseccentric — CHANGES_REQUESTED** [review]
Please see comments. :)

**Comment by parseccentric** [comment]
Please also write "F i x e s #41" in the first paragraph of the PR description :)

**Comment by ho-yi-shiuan** [comment]
@parseccentric I have fixed the errors, the dropdowns for data request are working well. Please review my code, thanks!
